// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbawuUc0QpjSChzgohoYDSqPl21mBFzkg',
    appId: '1:970756107467:web:ba6860c7cafa67b747ff4e',
    messagingSenderId: '970756107467',
    projectId: 'billbuddyapp-07',
    authDomain: 'billbuddyapp-07.firebaseapp.com',
    storageBucket: 'billbuddyapp-07.appspot.com',
    measurementId: 'G-V468F1W3R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIpgKhItPDWF5iz5DleBWtrJ698U_6g48',
    appId: '1:970756107467:android:e8403bcc8f9ceaaf47ff4e',
    messagingSenderId: '970756107467',
    projectId: 'billbuddyapp-07',
    storageBucket: 'billbuddyapp-07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4vdzkmRUL6vzFcMPEpoXkE4n1B44UuPA',
    appId: '1:970756107467:ios:c8f9b482a9f2ab3847ff4e',
    messagingSenderId: '970756107467',
    projectId: 'billbuddyapp-07',
    storageBucket: 'billbuddyapp-07.appspot.com',
    iosBundleId: 'com.example.brahmanapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4vdzkmRUL6vzFcMPEpoXkE4n1B44UuPA',
    appId: '1:970756107467:ios:16310539a5f4bdf847ff4e',
    messagingSenderId: '970756107467',
    projectId: 'billbuddyapp-07',
    storageBucket: 'billbuddyapp-07.appspot.com',
    iosBundleId: 'com.example.brahmanapp.RunnerTests',
  );
}
